#define F_blitComtoDisplay 35
#define F_bus_Read8 -122
#define F_bus_Write8 -121
#define F_charheight 29
#define F_charwidth 30
#define F_file_CallFunction 25
#define F_file_Close -431
#define F_file_Count 1
#define F_file_Dir 2
#define F_file_Erase 3
#define F_file_Error -424
#define F_file_Exec 4
#define F_file_Exists 5
#define F_file_FindFirst 6
#define F_file_FindFirstRet 36
#define F_file_FindNext -428
#define F_file_FindNextRet 37
#define F_file_GetC -441
#define F_file_GetS 7
#define F_file_GetW -443
#define F_file_Image -438
#define F_file_Index -434
#define F_file_LoadFunction 8
#define F_file_LoadImageControl 9
#define F_file_Mount -452
#define F_file_Open 10
#define F_file_PlayWAV 11
#define F_file_PutC 31
#define F_file_PutS 32
#define F_file_PutW -442
#define F_file_Read 12
#define F_file_Rewind -447
#define F_file_Run 13
#define F_file_ScreenCapture -439
#define F_file_Seek -433
#define F_file_Size 14
#define F_file_Tell 15
#define F_file_Unmount -453
#define F_file_Write 16
#define F_gfx_BevelShadow -196
#define F_gfx_BevelWidth -195
#define F_gfx_BGcolour -184
#define F_gfx_Button 17
#define F_gfx_ChangeColour -151
#define F_gfx_Circle -136
#define F_gfx_CircleFilled -137
#define F_gfx_Clipping -186
#define F_gfx_ClipWindow -150
#define F_gfx_Cls -126
#define F_gfx_Contrast -192
#define F_gfx_Ellipse -153
#define F_gfx_EllipseFilled -154
#define F_gfx_FrameDelay -189
#define F_gfx_Get -182
#define F_gfx_GetPixel -139
#define F_gfx_Line -131
#define F_gfx_LinePattern -193
#define F_gfx_LineTo -129
#define F_gfx_MoveTo -127
#define F_gfx_Orbit 18
#define F_gfx_OutlineColour -191
#define F_gfx_Panel -161
//#define F_gfx_PenSize -183
#define F_gfx_Polygon 19
#define F_gfx_PolygonFilled 20
#define F_gfx_Polyline 21
#define F_gfx_PutPixel -138
#define F_gfx_Rectangle -134
#define F_gfx_RectangleFilled -135
#define F_gfx_ScreenCopyPaste -163
#define F_gfx_ScreenMode -190
#define F_gfx_Set -125
#define F_gfx_SetClipRegion -152
#define F_gfx_Slider -162
#define F_gfx_Transparency -188
#define F_gfx_TransparentColour -187
#define F_gfx_Triangle -140
#define F_gfx_TriangleFilled -167
#define F_img_ClearAttributes -383
#define F_img_Darken -377
#define F_img_Disable -376
#define F_img_Enable -375
#define F_img_GetWord -380
#define F_img_Lighten -378
#define F_img_SetAttributes -382
#define F_img_SetPosition -374
#define F_img_SetWord -379
#define F_img_Show -381
#define F_img_Touched -384
#define F_media_Flush -218
#define F_media_Image -217
#define F_media_Init -219
#define F_media_RdSector 22
#define F_media_ReadByte -213
#define F_media_ReadWord -214
#define F_media_SetAdd -209
#define F_media_SetSector -210
#define F_media_Video -207
#define F_media_VideoFrame -208
#define F_media_WriteByte -215
#define F_media_WriteWord -216
#define F_media_WrSector 23
#define F_mem_Free -417
#define F_mem_Heap -418
#define F_pin_HI -113
#define F_pin_LO -114
#define F_pin_Read -116
#define F_pin_Set -112
#define F_putCH -2
#define F_putstr 24
#define F_readString 34
#define F_setbaudWait 38
#define F_snd_BufSize -461
#define F_snd_Continue -464
#define F_snd_Pause -463
#define F_snd_Pitch -460
#define F_snd_Playing -465
#define F_snd_Stop -462
#define F_snd_Volume -459
#define F_sys_GetModel 26
#define F_sys_GetPmmC 28
#define F_sys_GetVersion 27
#define F_sys_Sleep -403
#define F_touch_DetectRegion -406
#define F_touch_Get -408
#define F_touch_Set -407
#define F_txt_Attributes -31
#define F_txt_BGcolour -19
#define F_txt_Bold -27
#define F_txt_FGcolour -18
#define F_txt_FontID -20
#define F_txt_Height -22
#define F_txt_Inverse -29
#define F_txt_Italic -28
#define F_txt_MoveCursor -16
#define F_txt_Opacity -26
#define F_txt_Set -17
#define F_txt_Underline -30
#define F_txt_Width -21
#define F_txt_Wrap -32
#define F_txt_Xgap -23
#define F_txt_Ygap -24
#define F_writeString 33
